apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: paas
  name: ms-products
  labels:
    app: ui
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
      version: v1
  template:
    metadata:
      labels:
        app: ui
        version: v1
    spec:
      containers:
      - name: ms-products
        image: edhriacr2022.azurecr.io/ms-products:1.0
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  namespace: paas
  name: ms-products
spec:
 
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001